rewrite:
  users:
    email: "'faker.Internet().Email()'"
    password: "'faker.Lorem().Bytes(40)'"
    username: "'faker.Internet().Email()'"
    name: "'faker.Person().Name()'"

nodata:
  - actions
  - exports
  - tokens

ignore:
  - advertisers
  - transactions
  - cache

where:
  users: |-
    id < 5000
